Models/Customer.cs
namespace BankManagement.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
public class Customer
{   
    public int Id { get; set; }
    [Required(ErrorMessage = "Please enter first name")]  
    [Display(Name = "First Name")]  
    [StringLength(25)] 
    public string? FirstName { get; set; }
    [Required(ErrorMessage = "Please enter last name")]  
    [Display(Name = "Last Name")]  
    [StringLength(25)]   
    public string? LastName { get; set; }
    [Required(ErrorMessage = "Please enter Address")]    
    [StringLength(300)] 
    public string? Address { get; set; }
     [Required(ErrorMessage = "Please enter Adhar Number")] 
     [Display(Name = "Adhar Number")] 
     [RegularExpression(@"^(\d{12})$", ErrorMessage = "Entered adhar format is not valid.")]
    public string? AdharNumber { get; set; }
    [Required(ErrorMessage = "Please enter Pan Number")]
    [RegularExpression(@"^(\d{12})$", ErrorMessage = "Entered pan format is not valid.")]
    [Display(Name = "Pan Number")]  
    public string?  PanNumber { get; set; }
    [Required(ErrorMessage = "Please enter PhoneNumber")] 
    [Display(Name = "Phone Number")] 
    [DataType(DataType.PhoneNumber)]
    public string?  PhoneNumber { get; set; }
    [Required(ErrorMessage = "Please enter Email Address")] 
    [DataType(DataType.EmailAddress)]
    public string? Email { get; set; }
    [Display(Name = "Date of Birth")]  
    [DataType(DataType.Date)]  
    [Required]
    [CustomAgeValidation(ErrorMessage = "Age less than 10 is not valid")]
     public DateTime? DateOfBirth {get; set;}
    
    [Required(ErrorMessage = "Please select Image")]
    [Display(Name = "Photo")]  
    public string? Image { get; set; }
    [Required(ErrorMessage = "Please select Signature")]
    [Display(Name = "Sign")] 
    public string? Signature{ get; set;}
    [NotMapped]
    public string FullName => FirstName + " " + LastName;
    public int?UserId{get;set;}
    public virtual User? User { get; set; }
   public virtual ICollection<RegisteredPayee>? RegisteredPayees { get; set; }
   public virtual ICollection<Account>? Accounts { get; set; }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using bankmanagementsystem.Models;

namespace bankmanagementsystem.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/RegisteredPayeeController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BankManagement.Models;
using BankManagement.ViewModels;

namespace bankmanagementsystem.Controllers
{
    public class RegisteredPayeeController : Controller
    {
        private readonly BankManagementDbContext _context;

        public RegisteredPayeeController(BankManagementDbContext context)
        {
            _context = context;
        }

        // GET: RegisteredPayee
        public async Task<IActionResult> Index()
        {
            var bankManagementDbContext = _context.RegisteredPayees.Include(r => r.Customer).Where(m => m.Customer.UserId == HttpContext.Session.GetInt32("UserId")).ToList();
            return View(bankManagementDbContext);

        }
        public async Task<IActionResult> SentMoneyIndex(string searchName)
        {
            var mypayees = _context.RegisteredPayees.Include(r => r.Customer).Where(m => m.Customer.UserId == HttpContext.Session.GetInt32("UserId"));
             if (!string.IsNullOrEmpty(searchName))
            {
                mypayees = mypayees.Where(s => s.Name!.Contains(searchName));
            }
              var Payees = new RegisteredPayeeViewModel
            { 
                RegisteredPayees = await mypayees.ToListAsync()
            };
            return View(Payees);

        }
        [HttpPost]
        public string SentMoneyIndex(string searchName , bool notUsed)
        {
            return "From [HttpPost]SentMoneyIndex: filter on " + searchName;
        }


        // GET: RegisteredPayee/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registeredPayee = await _context.RegisteredPayees
                .Include(r => r.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (registeredPayee == null)
            {
                return NotFound();
            }

            return View(registeredPayee);
        }

        // GET: RegisteredPayee/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: RegisteredPayee/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(RegisteredPayee registeredPayee)
        {
            if (ModelState.IsValid)
            {
                if (registeredPayee.Bank == "Indian Bank")
                {
                    var registeredPayeeExists = _context.Accounts.FirstOrDefault(a => a.AccountNumber == registeredPayee.AccountNumber);
                    if (registeredPayeeExists != null)
                    {
                        registeredPayee.CustomerId = _context.Customers.FirstOrDefault(m => m.UserId == HttpContext.Session.GetInt32("UserId")).Id;
                        _context.Add(registeredPayee);
                        _context.SaveChanges();
                        return RedirectToAction("Home","Customer");
                    }
                    TempData["msg"] = "<script>alert('Account Number Doesnot Exist');</script>";
                }
                else
                {
                    registeredPayee.CustomerId = _context.Customers.FirstOrDefault(m => m.UserId == HttpContext.Session.GetInt32("UserId")).Id;
                    _context.Add(registeredPayee);
                    _context.SaveChanges();
                    return RedirectToAction("Home","Customer");
                }

            }
            return View(registeredPayee);
        }

        // GET: RegisteredPayee/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registeredPayee = await _context.RegisteredPayees.FindAsync(id);
            if (registeredPayee == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Address", registeredPayee.CustomerId);
            return View(registeredPayee);
        }

        // POST: RegisteredPayee/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Bank,AccountNumber,BranchCity,Name,NickName,CustomerId")] RegisteredPayee registeredPayee)
        {
            if (id != registeredPayee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(registeredPayee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegisteredPayeeExists(registeredPayee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "Id", "Address", registeredPayee.CustomerId);
            return View(registeredPayee);
        }

        // GET: RegisteredPayee/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var registeredPayee = await _context.RegisteredPayees
                .Include(r => r.Customer)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (registeredPayee == null)
            {
                return NotFound();
            }

            return View(registeredPayee);
        }

        // POST: RegisteredPayee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var registeredPayee = await _context.RegisteredPayees.FindAsync(id);
            _context.RegisteredPayees.Remove(registeredPayee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegisteredPayeeExists(int id)
        {
            return _context.RegisteredPayees.Any(e => e.Id == id);
        }
        public IActionResult CashTransfer(int id)
        {
            var registeredpayee = _context.RegisteredPayees.Include(r => r.Customer).FirstOrDefault(m => m.Id == id);
            TempData["registeredpayee"] = registeredpayee.Id;
            CashTransferViewModel model = new CashTransferViewModel();
            model.RegisteredPayee = registeredpayee;
            List<Account> accountlist = _context.Accounts.Where(a => a.Customer.UserId == HttpContext.Session.GetInt32("UserId")).ToList();
            ViewData["AccountList"] = accountlist.Select(x => new SelectListItem { Value = x.AccountNumber.ToString(), Text = x.AccountNumber.ToString() });
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CashTransfer(CashTransferViewModel model)
        {
            if (ModelState.IsValid)
            {
                var regpayee = TempData["registeredPayee"];
                var sender = _context.Accounts.FirstOrDefault(m => m.AccountNumber == Convert.ToInt32(model.SenderAccountNumber.Value));
                var receiver = _context.RegisteredPayees.Include(r => r.Customer).FirstOrDefault(m => m.Id == Convert.ToInt32(TempData["registeredpayee"]));
                if (model.Amount <= sender.Balance)
                {
                    MoneyTransfer moneytransfer= new MoneyTransfer{
                        RegisteredPayeeId= receiver.Id,
                        Amount=model.Amount,
                        SenderAccountNumber=model.SenderAccountNumber,
                    }; 
                    _context.Add(moneytransfer);
                    _context.SaveChanges();
                    TempData["MoneyID"] = moneytransfer.Id;
                    TempData.Keep("MoneyID");
                    return RedirectToAction("Review","MoneyTransfer");
                }
                return View();
            }
            return View();
        }
       
    }
}

Controllers/TransactionController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BankManagement.Models;

namespace bankmanagementsystem.Controllers
{
    public class TransactionController : Controller
    {
        private readonly BankManagementDbContext _context;

        public TransactionController(BankManagementDbContext context)
        {
            _context = context;
        }

        // GET: Transaction
        public async Task<IActionResult> Index()
        {
            var bankManagementDbContext = _context.Transactions.Include(t => t.Account);
            return View(await bankManagementDbContext.ToListAsync());
        }

        // GET: Transaction/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions
                .Include(t => t.Account)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // GET: Transaction/Create
        public IActionResult Create()
        {
            ViewData["AccountId"] = new SelectList(_context.Accounts, "Id", "Type");
            return View();
        }

        // POST: Transaction/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Date,Type,Amount,AccountNumber,AccountId")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                _context.Add(transaction);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccountId"] = new SelectList(_context.Accounts, "Id", "Type", transaction.AccountId);
            return View(transaction);
        }

        // GET: Transaction/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions.FindAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            ViewData["AccountId"] = new SelectList(_context.Accounts, "Id", "Type", transaction.AccountId);
            return View(transaction);
        }

        // POST: Transaction/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,Type,Amount,AccountNumber,AccountId")] Transaction transaction)
        {
            if (id != transaction.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transaction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransactionExists(transaction.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AccountId"] = new SelectList(_context.Accounts, "Id", "Type", transaction.AccountId);
            return View(transaction);
        }

        // GET: Transaction/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions
                .Include(t => t.Account)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // POST: Transaction/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var transaction = await _context.Transactions.FindAsync(id);
            _context.Transactions.Remove(transaction);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransactionExists(int id)
        {
            return _context.Transactions.Any(e => e.Id == id);
        }

         public IActionResult MyTransactions( )
        {
            List<Transaction> transactions= _context.Transactions.Where(t=>t.Account.Customer.UserId==HttpContext.Session.GetInt32("UserId")).ToList();
            return View(transactions.OrderByDescending(e => e.Date)); 
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult  MyTransactions(DateTime? start, DateTime? end){
  List<Transaction> transactions= _context.Transactions.Where(t=>t.Account.Customer.UserId==HttpContext.Session.GetInt32("UserId") && t.Date>= start && t.Date<= end ).ToList();         
        return View(transactions.OrderByDescending(e => e.Date));
       } 

    }
}

Views/Customer/Create.cshtml
@model BankManagement.ViewModels.CustomerViewModel

@{
    ViewData["Title"] = "Create";
    Layout="~/Views/Shared/_Auth_Layout.cshtml";
}

<div class="col-md-10 mx-auto py-4">
    <div class="card mt-2">
        <div class="card-header bg-primary text-uppercase text-white">
            <h4 class="text-center">Account Opening Form</h4>
        </div>
        <div class="card-body">
            <form enctype="multipart/form-data" asp-action="Create">
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="FirstName" class="control-label"></label>
                            <input asp-for="FirstName" class="form-control" />
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Address" class="control-label"></label>
                            <textarea asp-for="Address" class="form-control" rows="2"></textarea>
                            <span asp-validation-for="Address" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <label asp-for="AccountType" class="control-label"></label>
                    <div class="col-md-3">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="AccountType" value="Savings Account"
                                id="SavingsAccount" required>
                            <label class="form-check-label" for="SavingsAccount">Savings Account</label>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="AccountType"
                                value="Fixed Deposit " id="FixedAccount" required>
                            <label class="form-check-label" for="FixedAccount">Fixed Deposit</label>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="AccountType"
                                value="Recurring Deposit " id="RDAccount" required>
                            <label class="form-check-label" for="RDAccount">Recurring Deposit</label>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="AccountType"
                                value="Current Account" id="CurrentAccount" required>
                            <label class="form-check-label" for="CurrentAccount">Current Account</label>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="DateOfBirth" class="control-label"></label>
                            <input asp-for="DateOfBirth" type="Date" class="form-control" />
                            <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="PhoneNumber" class="control-label"></label>
                            <input asp-for="PhoneNumber" class="form-control" />
                            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="AdharNumber" class="control-label"></label>
                            <input asp-for="AdharNumber" class="form-control" />
                            <span asp-validation-for="AdharNumber" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="PanNumber" class="control-label"></label>
                            <input asp-for="PanNumber" class="form-control" />
                            <span asp-validation-for="PanNumber" class="text-danger"></span>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Image" class="control-label"></label>
                            <div class="custom-file">
                                <input asp-for="Image" class="custom-file-input" id="customFile">

                            </div>
                            <span asp-validation-for="Image" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label asp-for="Signature" class="control-label"></label>
                            <div class="custom-file">
                                <input asp-for="Signature" class="custom-file-input" id="customFile">

                            </div>
                            <span asp-validation-for="Signature" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="row mt-2">

                    <div class="form-group">
                        <input type="submit" value="submit" class="btn btn-sm btn-primary rounded-0 text-uppercase" />
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>

Views/Customer/Delete.cshtml
@model BankManagement.Models.Customer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FullName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FullName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AdharNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AdharNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PanNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PanNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Signature)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Signature)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Password)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Customer/Home.cshtml
@model BankManagement.Models.Customer

@{
    ViewData["Title"] = "Home";
    Layout = "~/Views/Shared/_Auth_Layout.cshtml";
}
<div class="container mt-5">
    <div class="row mt-5 mb-5">
        <div class="col-xl-1"></div>
        <div class="col-xl-2">
            <a class="text-decoration-none" asp-action="Create">
                <div class="card border-light mt-5 home">
                    <img class="card-img-top " src="/images/account.webp" alt="Card image cap" height="200px">
                    <div class="card-body text-center">
                        <h4 class="card-text  ">Create An Account</h4>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-2">
            <a class="text-decoration-none" asp-controller="Account" asp-action="MyAccounts">
                <div class="card  border-light mt-5 home">
                    <img class="card-img-top " src="/images/balance.webp" alt="Card image cap" height="200px">
                    <div class="card-body text-center">
                        <h4 class="card-text ">View All Accounts</h4>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-2">
            <a class="text-decoration-none" asp-controller="RegisteredPayee" asp-action="Create">
                <div class="card  border-light mt-5 home">
                    <img class="card-img-top " src="/images/bank.webp" alt="Card image cap" height="200px">
                    <div class="card-body text-center">
                        <h4 class=" card-text">Add Beneficiery</h4>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-xl-2">
           <a class="text-decoration-none" asp-area="" asp-controller="RegisteredPayee" asp-action="SentMoneyIndex">
                <div class="card  border-light mt-5 home">
                    <img class="card-img-top " src="/images/Money-transfer.jpg" alt="Card image cap" height="200px">
                    <div class="card-body text-center">
                        <h4 class="card-text ">SentMoney</h4>
                           </div>
                </div>
            </a>
                 
        </div>
        <div class="col-xl-2">
 <a class="text-decoration-none" asp-area="" asp-controller="Transaction" asp-action="MyTransactions">
                <div class="card  border-light mt-5 home">
                    <img class="card-img-top " src="/images/trans.webp" alt="Card image cap" height="200px">
                    <div class="card-body text-center">
                        <h4 class="card-text ">Transactions</h4>
                           </div>

                </div>
            </a>
        </div>
        <div class="col-xl-1"></div>
    </div>
</div>